box::use(
  stats[...]
)

# generated by {burglr}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# bca (copied from coxed:::bca)
# from coxed 0.3.3
#' @export
bca <- function(theta, conf.level = 0.95) {
  low <- (1 - conf.level) / 2
  high <- 1 - low
  sims <- length(theta)
  z.inv <- length(theta[theta < mean(theta)]) / sims
  z <- qnorm(z.inv)
  U <- (sims - 1) * (mean(theta, na.rm = TRUE) - theta)
  top <- sum(U^3)
  under <- 6 * (sum(U^2))^{
    3 / 2
  }
  a <- top / under
  lower.inv <- pnorm(z + (z + qnorm(low)) / (1 - a * (z + qnorm(low))))
  lower <- quantile(theta, lower.inv, names = FALSE)
  upper.inv <- pnorm(z + (z + qnorm(high)) / (1 - a * (z + qnorm(high))))
  upper <- quantile(theta, upper.inv, names = FALSE)
  return(c(lower, upper))
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# quantcut (copied from gtools:::quantcut)
# from gtools 3.8.2
#' @export
quantcut <- function(x, q = 4, na.rm = TRUE, ...) {
  if (length(q) == 1) {
    q <- seq(0, 1, length.out = q + 1)
  }
  quant <- quantile(x, q, na.rm = na.rm)
  dups <- duplicated(quant)
  if (any(dups)) {
    flag <- x %in% unique(quant[dups])
    retval <- ifelse(flag, paste("[", as.character(x), "]",
      sep = ""
    ), NA)
    uniqs <- unique(quant)
    reposition <- function(cut) {
      flag <- x >= cut
      if (sum(flag, na.rm = na.rm) == 0) {
        return(cut)
      } else {
        return(min(x[flag], na.rm = na.rm))
      }
    }
    newquant <- sapply(uniqs, reposition)
    retval[!flag] <- as.character(cut(x[!flag],
      breaks = newquant,
      include.lowest = TRUE, ...
    ))
    levs <- unique(retval[order(x)])
    retval <- factor(retval, levels = levs)
    mkpairs <- function(x) {
      sapply(x, function(y) {
        if (length(y) ==
          2) {
          y[c(2, 2)]
        } else {
          y[2:3]
        }
      })
    }
    pairs <- mkpairs(strsplit(levs, "[^0-9+\\.\\-]+"))
    rownames(pairs) <- c("lower.bound", "upper.bound")
    colnames(pairs) <- levs
    closed.lower <- rep(F, ncol(pairs))
    closed.upper <- rep(T, ncol(pairs))
    closed.lower[1] <- TRUE
    for (i in 2:ncol(pairs)) {
      if (pairs[1, i] == pairs[
        1,
        i - 1
      ] && pairs[1, i] == pairs[2, i - 1]) {
        closed.lower[i] <- FALSE
      }
    }
    for (i in 1:(ncol(pairs) - 1)) {
      if (pairs[2, i] == pairs[
        1,
        i + 1
      ] && pairs[2, i] == pairs[2, i + 1]) {
        closed.upper[i] <- FALSE
      }
    }
    levs <- ifelse(pairs[1, ] == pairs[2, ], pairs[1, ],
      paste(ifelse(closed.lower, "[", "("), pairs[1, ],
        ",", pairs[2, ], ifelse(closed.upper, "]", ")"),
        sep = ""
      )
    )
    levels(retval) <- levs
  } else {
    retval <- cut(x, quant, include.lowest = TRUE, ...)
  }
  return(retval)
}
