box::use(
  stats[...]
)

# generated by {burglr}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# bca (copied from coxed:::bca)
# from coxed 0.3.3
#' @export
bca <- function(theta, conf.level = 0.95) {
  low <- (1 - conf.level) / 2
  high <- 1 - low
  sims <- length(theta)
  z.inv <- length(theta[theta < mean(theta)]) / sims
  z <- qnorm(z.inv)
  U <- (sims - 1) * (mean(theta, na.rm = TRUE) - theta)
  top <- sum(U^3)
  under <- 6 * (sum(U^2))^{
    3 / 2
  }
  a <- top / under
  lower.inv <- pnorm(z + (z + qnorm(low)) / (1 - a * (z + qnorm(low))))
  lower <- quantile(theta, lower.inv, names = FALSE)
  upper.inv <- pnorm(z + (z + qnorm(high)) / (1 - a * (z + qnorm(high))))
  upper <- quantile(theta, upper.inv, names = FALSE)
  return(c(lower, upper))
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# quantcut (copied from gtools:::quantcut)
# from gtools 3.8.2
#' @export
quantcut <- function(x, q = 4, na.rm = TRUE, ...) {
  if (length(q) == 1) {
    q <- seq(0, 1, length.out = q + 1)
  }
  quant <- quantile(x, q, na.rm = na.rm)
  dups <- duplicated(quant)
  if (any(dups)) {
    flag <- x %in% unique(quant[dups])
    retval <- ifelse(flag, paste("[", as.character(x), "]",
      sep = ""
    ), NA)
    uniqs <- unique(quant)
    reposition <- function(cut) {
      flag <- x >= cut
      if (sum(flag, na.rm = na.rm) == 0) {
        return(cut)
      } else {
        return(min(x[flag], na.rm = na.rm))
      }
    }
    newquant <- sapply(uniqs, reposition)
    retval[!flag] <- as.character(cut(x[!flag],
      breaks = newquant,
      include.lowest = TRUE, ...
    ))
    levs <- unique(retval[order(x)])
    retval <- factor(retval, levels = levs)
    mkpairs <- function(x) {
      sapply(x, function(y) {
        if (length(y) ==
          2) {
          y[c(2, 2)]
        } else {
          y[2:3]
        }
      })
    }
    pairs <- mkpairs(strsplit(levs, "[^0-9+\\.\\-]+"))
    rownames(pairs) <- c("lower.bound", "upper.bound")
    colnames(pairs) <- levs
    closed.lower <- rep(F, ncol(pairs))
    closed.upper <- rep(T, ncol(pairs))
    closed.lower[1] <- TRUE
    for (i in 2:ncol(pairs)) {
      if (pairs[1, i] == pairs[
        1,
        i - 1
      ] && pairs[1, i] == pairs[2, i - 1]) {
        closed.lower[i] <- FALSE
      }
    }
    for (i in 1:(ncol(pairs) - 1)) {
      if (pairs[2, i] == pairs[
        1,
        i + 1
      ] && pairs[2, i] == pairs[2, i + 1]) {
        closed.upper[i] <- FALSE
      }
    }
    levs <- ifelse(pairs[1, ] == pairs[2, ], pairs[1, ],
      paste(ifelse(closed.lower, "[", "("), pairs[1, ],
        ",", pairs[2, ], ifelse(closed.upper, "]", ")"),
        sep = ""
      )
    )
    levels(retval) <- levs
  } else {
    retval <- cut(x, quant, include.lowest = TRUE, ...)
  }
  return(retval)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# theme_apa (copied from papaja:::theme_apa)
# from papaja 0.1.0.9997
#' @export
theme_apa <- function(base_size = 12, base_family = "", box = FALSE) {
  adapted_theme <- ggplot2::theme_bw(base_size, base_family) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        size = ggplot2::rel(1.1),
        margin = ggplot2::margin(
          0, 0, ggplot2::rel(14),
          0
        )
      ), axis.title.x = ggplot2::element_text(
        size = ggplot2::rel(1),
        lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(
          ggplot2::rel(12),
          0, 0, 0
        )
      ), axis.title.y = ggplot2::element_text(
        size = ggplot2::rel(1),
        lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(
          0,
          ggplot2::rel(12), 0, 0
        )
      ), axis.title.y.right = ggplot2::element_text(
        size = ggplot2::rel(1),
        lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(
          0,
          0, 0, ggplot2::rel(12)
        )
      ), axis.ticks.length = ggplot2::unit(
        ggplot2::rel(6),
        "points"
      ), axis.text = ggplot2::element_text(size = ggplot2::rel(0.9)),
      axis.text.x = ggplot2::element_text(
        size = ggplot2::rel(1),
        margin = ggplot2::margin(
          ggplot2::rel(6), 0,
          0, 0
        )
      ), axis.text.y = ggplot2::element_text(
        size = ggplot2::rel(1),
        margin = ggplot2::margin(
          0, ggplot2::rel(6),
          0, 0
        )
      ), axis.text.y.right = ggplot2::element_text(
        size = ggplot2::rel(1),
        margin = ggplot2::margin(0, 0, 0, ggplot2::rel(6))
      ),
      axis.line = ggplot2::element_line(), legend.title = ggplot2::element_text(),
      legend.key = ggplot2::element_rect(fill = NA, color = NA),
      legend.key.width = ggplot2::unit(
        ggplot2::rel(20),
        "points"
      ), legend.key.height = ggplot2::unit(
        ggplot2::rel(20),
        "points"
      ), legend.margin = ggplot2::margin(
        t = ggplot2::rel(16),
        r = ggplot2::rel(16), b = ggplot2::rel(16), l = ggplot2::rel(16),
        unit = "points"
      ), panel.spacing = ggplot2::unit(
        ggplot2::rel(14),
        "points"
      ), panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor.x = ggplot2::element_blank(), panel.grid.major.y = ggplot2::element_blank(),
      panel.grid.minor.y = ggplot2::element_blank(), strip.background = ggplot2::element_rect(
        fill = NA,
        color = NA
      ), strip.text.x = ggplot2::element_text(
        size = ggplot2::rel(1.2),
        margin = ggplot2::margin(
          0, 0, ggplot2::rel(10),
          0
        )
      ), strip.text.y = ggplot2::element_text(
        size = ggplot2::rel(1.2),
        margin = ggplot2::margin(0, 0, 0, ggplot2::rel(10))
      )
    )
  if (box) {
    adapted_theme <- adapted_theme + ggplot2::theme(panel.border = ggplot2::element_rect(color = "black"))
  }
  else {
    adapted_theme <- adapted_theme + ggplot2::theme(panel.border = ggplot2::element_blank())
  }
  adapted_theme
}
